# Generated by Django 5.2.17 on 2026-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Niteesh Patel', max_length=120)),
                ('headline', models.CharField(default='An Artist', max_length=160)),
                ('bio', models.TextField(default='Creative thinker and artist building visual stories.')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('hero_image', models.ImageField(blank=True, upload_to='profile/')),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'portfolio profile',
                'verbose_name_plural': 'portfolio profile',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('works', 'My Works'), ('achievements', 'Achievements'), ('personality', 'Personality'), ('college', 'College')], default='works', max_length=20)),
                ('image', models.ImageField(upload_to='projects/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'display_order', '-created_at'],
            },
        ),
    ]
